reown-com/reown-swift

- Sources/WalletConnectRelay/Dispatching.swift
- Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift
- Tests/RelayerTests/DispatcherTests.swift
> socket fix

- Sources/WalletConnectRelay/Dispatching.swift
- reown-swift.podspec
> fix cocoapods

- .github/workflows/cocoapods.yml
> fix podspec

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/Shared/Signer/Signer.swift
- Example/WalletApp/BusinessLayer/SmartAccountManager.swift
- Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift
- Example/WalletApp/PresentationLayer/Wallet/Settings/SettingsPresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/Settings/SettingsView.swift
adds toggle for enabling safe and simple account
Resolves # (issue)
> Smart account enabler

- Example/IntegrationTests/Sign/SignClientTests.swift
- Example/RelayIntegrationTests/RelayClientEndToEndTests.swift
- Sources/WalletConnectRelay/BundleFinder.swift
- Sources/WalletConnectRelay/EnvironmentInfo.swift
- Sources/WalletConnectRelay/RelayClient.swift
- Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift
- Sources/WalletConnectRelay/SocketConnectionHandler/WebSocket.swift
- Sources/WalletConnectRelay/SubscriptionsTracker.swift
- Tests/RelayerTests/AutomaticSocketConnectionHandlerTests.swift
> Ci improvements

- Sources/WalletConnectRelay/BundleFinder.swift
> cocoapod fix

- Sources/WalletConnectKMS/Serialiser/Serializer.swift
- Sources/WalletConnectSign/Engine/Common/DeleteSessionService.swift
> delete session on serializer error

- Example/DApp/SceneDelegate.swift
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sources/ReownAppKit/Core/AppKit.swift
> fix crash when coinbase disabled

- Example/AppKitLab/AppKitLabApp.swift
> update appkit lab

- Sources/ReownAppKit/Core/W3MAPIInteractor.swift
- Sources/ReownAppKit/Networking/Web3ModalAPI.swift
> fix exclude wallets

- Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift
> register push for notify

- Example/WalletApp/ApplicationLayer/ConfigurationService.swift
- Sources/WalletConnectRelay/RelayClient.swift
- Tests/RelayerTests/RelayClientTests.swift
> fix subscribe ack

- Example/IntegrationTests/Sign/SignClientTests.swift
> add logs to integration tests, fix some tests

- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/Shared/Signer/Signer.swift
- Example/WalletApp/BusinessLayer/ChainAbstractionService.swift
- Example/WalletApp/PresentationLayer/Wallet/CATransactionModal/CATransactionModule.swift
- Example/WalletApp/PresentationLayer/Wallet/CATransactionModal/CATransactionPresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/Main/MainRouter.swift
- Makefile
- Package.resolved
- Package.swift
- Sources/ReownWalletKit/SmartAccount/SafesManager.swift
- Sources/ReownWalletKit/WalletKitClient.swift
- Sources/WalletConnectPairing/Services/Wallet/WalletPairService.swift
- Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift
- Sources/WalletConnectSign/WalletConnectError.swift
- Sources/WalletConnectSigner/Verifier/MessageVerifier.swift
- Sources/WalletConnectSigner/Verifier/MessageVerifierFactory.swift
> Enable 6492 verification

- Example/Shared/Signer/ETHSigner.swift
- Sources/WalletConnectUtils/TVFCollector.swift
- Tests/WalletConnectUtilsTests/TVFCollectorTests.swift
> add call data check on tvf

- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.swift
> update yttrium to 0.8.15

- Sources/ReownAppKit/Core/AppKit.swift
- Sources/ReownAppKit/Core/W3MAPIInteractor.swift
- Sources/ReownAppKit/Networking/Web3ModalAPI.swift
> add include param

- funding.json
> chore: verifies repository ownership

- Example/DApp/SceneDelegate.swift
- Sources/ReownAppKit/Core/W3MAPIInteractor.swift
- Sources/ReownAppKit/Networking/Web3ModalAPI.swift
- Sources/ReownAppKit/Screens/ConnectWallet/AllWalletsView.swift
> appkit add recommended wallets

- Package.resolved
- Sources/WalletConnectUtils/SolanaSignatureExtractor.swift
- Sources/WalletConnectUtils/TVFCollector.swift
- Tests/WalletConnectUtilsTests/SolanaSignatureExtractorTests.swift
- Tests/WalletConnectUtilsTests/TVFCollectorTests.swift
> Fix encoding issue

- .swiftpm/xcode/xcshareddata/xcschemes/YttriumWrapper.xcscheme
- Example/DApp/Modules/Sign/SessionAccount/SessionAccountPresenter.swift
- Sources/ReownAppKit/Screens/ConnectWallet/AllWalletsView.swift
> Appkit improvements

- Example/IntegrationTests/Sign/SignClientTests.swift
- Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift
- Sources/ReownAppKit/Core/AppKitClient.swift
- Sources/ReownWalletKit/WalletKitClient.swift
- Sources/WalletConnectSign/Auth/Link/ApproveSessionAuthenticateUtil.swift
- Sources/WalletConnectSign/Auth/Services/App/AuthResponseSubscriber.swift
- Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift
- Sources/WalletConnectSign/LinkAndRelayDispatchers/SessionRequester.swift
- Sources/WalletConnectSign/LinkAndRelayDispatchers/WalletServiceFinder.swift
- Sources/WalletConnectSign/LinkAndRelayDispatchers/WalletServiceSessionRequestable.swift
- Sources/WalletConnectSign/LinkAndRelayDispatchers/WalletServiceSessionRequester.swift
- Sources/WalletConnectSign/Services/App/AppProposeService.swift
- Sources/WalletConnectSign/Session.swift
- Sources/WalletConnectSign/Sign/SignClient.swift
- Sources/WalletConnectSign/Sign/SignClientProtocol.swift
- Sources/WalletConnectSign/Types/Session/SessionProposal.swift
- Sources/WalletConnectSign/Types/Session/SessionType.swift
- Sources/WalletConnectSign/Types/Session/WCSession.swift
- Sources/WalletConnectUtils/TVFCollector.swift
- Tests/WalletConnectSignTests/AutoNamespacesValidationTests.swift
- Tests/WalletConnectSignTests/Mocks/WCSessionStorageMock.swift
- Tests/WalletConnectSignTests/Mocks/WalletServiceSessionRequesterMock.swift
- Tests/WalletConnectSignTests/SessionRequesterTests.swift
- Tests/WalletConnectSignTests/Stub/Session+Stub.swift
- Tests/WalletConnectSignTests/WalletServiceFinderTests.swift
Caip-345 support
Resolves # (issue)
> Scoped properties - wallet service delegation - caip-345

- Sources/WalletConnectPairing/Types/AppMetadata.swift
- Tests/WalletConnectPairingTests/AppMetadataTests.swift
> default metadata url

- Sources/ReownAppKit/Core/AppKitClient.swift
> fix appkit coinbase crash

- Example/DApp/SceneDelegate.swift
Update react native wallet universal link
> Update rn wallet link

- .github/workflows/ui-tests.yml
> fix workflow

- .github/workflows/ui-tests.yml
> update uitests workflow

- Example/ExampleApp.xcodeproj/xcshareddata/xcschemes/UITests.xcscheme
- Example/UITests/Engine/DAppEngine.swift
- Example/UITests/Engine/WalletEngine.swift
- Example/UITests/Extensions/XCUIElement.swift
- Example/UITests/Regression/RegressionTests.swift
> UI tests with web

- Example/ExampleApp.xcodeproj/xcshareddata/xcschemes/UITests.xcscheme
- Example/UITests/Regression/UITestsWalletAgainstAppKitWeb.swift
> order tests with safari

- Sources/WalletConnectRelay/tvf/StacksTVFCollector.swift
- Tests/RelayerTests/StacksTVFCollectorTests.swift
- Tests/RelayerTests/TVFCollectorTests.swift
> fix stacks tvf

- Example/DApp/Modules/Sign/SignInteractor.swift
- Example/DApp/Modules/Sign/SignPresenter.swift
- Sources/ReownAppKit/Core/AppKit.swift
- Sources/WalletConnectSign/Services/App/AppProposeService.swift
- Sources/WalletConnectSign/Services/App/NamespaceMerger.swift
- Sources/WalletConnectSign/Sign/SignClient.swift
- Tests/WalletConnectSignTests/NamespaceMergerTests.swift
> implement namaspaces merger

- Sources/WalletConnectSign/Auth/Link/LinkEnvelopesDispatcher.swift
> fix query items override

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/Shared/Signer/Signer.swift
- Example/Shared/Signer/StacksSigner.swift
- Example/WalletApp/BusinessLayer/StacksAccointStorage.swift
- Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift
- Example/WalletApp/PresentationLayer/Wallet/Settings/SettingsPresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/Settings/SettingsView.swift
- Example/WalletApp/PresentationLayer/Wallet/Welcome/WelcomeInteractor.swift
- Example/WalletApp/PresentationLayer/Wallet/Welcome/WelcomePresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/Welcome/WelcomeView.swift
- Package.resolved
- Package.swift
- Sources/WalletConnectRelay/tvf/StacksTVFCollector.swift
- Tests/RelayerTests/StacksTVFCollectorTests.swift
- Tests/RelayerTests/TVFCollectorTests.swift
> Stacks integration
